"""
Standardizes naming and description of dataframe columns
Format = NAME = 'label', 'units','description'
"""

OUTPUT_DF_DESC = {
    "segment_id": ("Index for the current drive cycle segment", ""),
    "start_time": ("Time from t=0 at which the segment starts", "s"),
    "duration": ("Duration of the drive cycle segment", "s"),
    "segment_type": ("Label for if the segment is accelerating, etc.", ""),
    "start_v": ("Velocity at the beginning of the segment", "m/s"),
    "end_v": ("Velocity at the end of the segment", "m/s"),
    "avg_v": ("Average velocity", "m/s"),
    "avg_vv": ("Average square of the segment velocity", "m2/s2"),
    "acceleration": ("Acceleration during the segment", "m/s2"),
    "delta_alt": ("Change in altitude during the segment", "m/s"),
    "avg_alt": ("Average altitude during the segment", "m/s"),
    "delta_d": ("Linear distance covered", "m/s"),
    "vehicle_mass": ("Mass of the vehicle", "kg"),
    "air_density": ("Density of air during the segment", "kg/m3"),
    "loss_rolling": ("Energy lost to rolling resistance", "J"),
    "loss_drag": ("Energy lost to aerodynamic drag", "J"),
    "kinetic_start": ("Kinetic energy at the beginning of the segment", "J"),
    "kinetic_end": ("Kinetic energy at the end of the segment", "J"),
    "kinetic_delta": ("Change in kinetic energy", "J"),
    "grav_delta": ("Change in grav potential energy", "J"),
    "energy_wheel": ("Energy flux through the wheel", "J"),
    "power_wheel": ("Power applied at the wheel", "W"),
    "force_wheel": ("Force applied at the wheel", "N.m"),
    "omega_wheel": ("Rotational velocity at wheel", "rad/s"),
    "torque_wheel": ("Torque applied at the wheel", "N.m"),
    "electric_demand_accessory": ("Electric energy demand of accessories", "J"),
    "torque_driveshaft": ("Torque applied at the driveshaft", "N.m"),
    "power_driveshaft": ("Power applied at the driveshaft", "W"),
    "omega_driveshaft": ("Rotational velocity of the driveshaft", "rad/s"),
    "power_engine_driveshaft": ("Power demand of the engine to driveshaft", "W"),
    "energy_engine_driveshaft": ("Energy flux from engine to driveshaft", "J"),
    "torque_engine_driveshaft": ("Torque from engine to driveshaft", "N.m"),
    "torque_brake": ("Braking torque", "N.m"),
    "power_brake": ("Power required for braking", "W"),
    "loss_friction_brake": ("Friction loss from the brakes", "J"),
    "energy_engine_alternator": ("Energy flux from engine to alternator", "J"),
    "energy_from_engine": ("Total energy from the engine", "J"),
    "input_thermal": ("Thermal input to engine via fuel", "J"),
    "input_petrol": ("Petrol consumption", "L"),
}
